from typing import Any
from contextlib import AbstractContextManager

class _Config:
    config_file_name: str | None
    config_ini_section: str

    def get_main_option(self, key: str) -> str: ...
    def set_main_option(self, key: str, value: str) -> None: ...
    def get_section(self, name: str) -> dict[str, Any] | None: ...

config: _Config


def configure(*args: Any, **kwargs: Any) -> None: ...

def begin_transaction() -> AbstractContextManager[Any]: ...

def run_migrations() -> None: ...

def is_offline_mode() -> bool: ...
