"""add document table

Revision ID: 17b3833ecf41
Revises: 4a684f791aee
Create Date: 2026-01-07 15:09:27.366333

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17b3833ecf41'
down_revision = '4a684f791aee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_created_at'), 'activity_log', ['created_at'], unique=False)
    op.create_table('activity_log_archive',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_archive_created_at'), 'activity_log_archive', ['created_at'], unique=False)
    op.create_table('document',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.Column('storage_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_index('ix_document_organization_id', 'document', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_membership_user_org', 'membership', ['user_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_membership_user_org', 'membership', type_='unique')
    op.drop_index('ix_document_organization_id', table_name='document')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_activity_log_archive_created_at'), table_name='activity_log_archive')
    op.drop_table('activity_log_archive')
    op.drop_index(op.f('ix_activity_log_created_at'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
