"""add unique constraint on app_user.email

Revision ID: 2158c52d75b6
Revises: 17b3833ecf41
Create Date: 2026-01-08 19:16:02.920894

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '2158c52d75b6'
down_revision = '17b3833ecf41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_app_user_email', 'app_user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_app_user_email', 'app_user', type_='unique')
    # ### end Alembic commands ###
