"""initial

Revision ID: 4a684f791aee
Revises:
Create Date: 2026-01-03 22:41:18.678938
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a684f791aee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "membership",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_app_user_created_at", "app_user", ["created_at"], unique=False)
    op.create_index(
        "ix_organization_created_at", "organization", ["created_at"], unique=False
    )
    op.create_index(
        "ix_membership_created_at", "membership", ["created_at"], unique=False
    )
    op.create_index(
        "ix_membership_organization_id", "membership", ["organization_id"], unique=False
    )
    op.create_index("ix_membership_user_id", "membership", ["user_id"], unique=False)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER app_user_set_updated_at
        BEFORE UPDATE ON app_user
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )
    op.execute(
        """
        CREATE TRIGGER organization_set_updated_at
        BEFORE UPDATE ON organization
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )
    op.execute(
        """
        CREATE TRIGGER membership_set_updated_at
        BEFORE UPDATE ON membership
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS membership_set_updated_at ON membership")
    op.execute("DROP TRIGGER IF EXISTS organization_set_updated_at ON organization")
    op.execute("DROP TRIGGER IF EXISTS app_user_set_updated_at ON app_user")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at")
    op.drop_index("ix_membership_user_id", table_name="membership")
    op.drop_index("ix_membership_organization_id", table_name="membership")
    op.drop_index("ix_membership_created_at", table_name="membership")
    op.drop_index("ix_organization_created_at", table_name="organization")
    op.drop_index("ix_app_user_created_at", table_name="app_user")
    op.drop_table("membership")
    op.drop_table("organization")
    op.drop_table("app_user")
    # ### end Alembic commands ###
