"""normalize_kratos_identity_id_constraints

Revision ID: 9c89a84af0d3
Revises: ffac4fcfdc07
Create Date: 2026-01-29 22:44:37.705333

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c89a84af0d3'
down_revision = 'ffac4fcfdc07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_app_user_kratos_identity_id'), table_name='app_user')
    op.drop_constraint(op.f('uq_app_user_kratos_identity_id'), 'app_user', type_='unique')
    op.create_index(op.f('ix_app_user_kratos_identity_id'), 'app_user', ['kratos_identity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_kratos_identity_id'), table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_kratos_identity_id'), 'app_user', ['kratos_identity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_app_user_kratos_identity_id'), 'app_user', ['kratos_identity_id'], unique=False)
    # ### end Alembic commands ###
