"""add review strategy columns

Three JSONB string arrays, one per side of the strategy contract: what a repo
asks for (repo_policy.default_strategies), what a job inherited at enqueue time
(review_job.requested_strategies), and what a client is willing to run
(review_client.offered_strategies).

server_default='[]' with nullable=False is what backfills existing rows, so no
data migration accompanies this — and an empty array is the match-any sentinel,
which means every row already in the table keeps leasing exactly as it did.

Revision ID: e06bf706f804
Revises: d4e5f6a7b8c9
Create Date: 2026-08-16 05:39:13.537040

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e06bf706f804'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_policy', sa.Column('default_strategies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('review_client', sa.Column('offered_strategies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('review_job', sa.Column('requested_strategies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_job', 'requested_strategies')
    op.drop_column('review_client', 'offered_strategies')
    op.drop_column('repo_policy', 'default_strategies')
    # ### end Alembic commands ###
