#!/usr/bin/env bash
# Open a PR on the demo repo on command, so a demo never waits on real traffic.
#
#   scripts/demo-pr.sh            # open a PR, print its URL
#   scripts/demo-pr.sh --close N  # close PR N and delete its branch
#   scripts/demo-pr.sh --clean    # close every open demo PR
#
# The demo repo is private and throwaway, and nothing there auto-merges — so a
# queued job stays leasable for as long as the demo needs it, unlike
# claude-workspace where PRs merge in about four minutes.
set -euo pipefail

REPO="${DEMO_REPO:-mattwwarren/review-bingo-demo}"
WORKDIR="${DEMO_WORKDIR:-$HOME/.cache/review-bingo-demo}"

say() { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }

if [[ "${1:-}" == "--close" ]]; then
  [[ -n "${2:-}" ]] || { echo "usage: $0 --close <pr-number>" >&2; exit 2; }
  gh pr close "$2" --repo "$REPO" --delete-branch
  exit 0
fi

if [[ "${1:-}" == "--clean" ]]; then
  for n in $(gh pr list --repo "$REPO" --state open --json number --jq '.[].number'); do
    echo "closing #$n"
    gh pr close "$n" --repo "$REPO" --delete-branch
  done
  exit 0
fi

if [[ ! -d "$WORKDIR/.git" ]]; then
  say "Cloning $REPO to $WORKDIR"
  # gh, not git: the demo repo is private, and a bare https clone has no
  # credentials to offer — it fails asking for a username.
  gh repo clone "$REPO" "$WORKDIR" -- --quiet
fi

cd "$WORKDIR"
git fetch --quiet origin
DEFAULT_BRANCH="$(gh repo view "$REPO" --json defaultBranchRef --jq '.defaultBranchRef.name')"
git checkout --quiet "$DEFAULT_BRANCH"
git reset --quiet --hard "origin/$DEFAULT_BRANCH"

STAMP="$(date +%Y%m%d-%H%M%S)"
BRANCH="demo-$STAMP"
FILE="samples/refund_$STAMP.py"

git checkout --quiet -b "$BRANCH"
mkdir -p samples

# Deliberately flawed: gives a real reviewer (REVIEW_CMD=claude -p) something
# genuine to find, so a live demo shows findings rather than "looks good".
cat > "$FILE" <<'PY'
"""Refund helper for the demo grid."""


def refund_amount(total_cents, refund_pct):
    """Return the refund in cents for a percentage of an order."""
    return total_cents * refund_pct / 100


def split_refund(total_cents, ways):
    """Split a refund evenly between payment methods."""
    return [total_cents / ways for _ in range(ways)]
PY

git add "$FILE"
git -c user.name="review-bingo demo" -c user.email="demo@review-bingo.invalid" \
  commit --quiet -m "demo($STAMP): add refund helper"
git push --quiet -u origin "$BRANCH" >/dev/null 2>&1

say "Opening PR on $REPO"
gh pr create --repo "$REPO" --head "$BRANCH" --base "$DEFAULT_BRANCH" \
  --title "demo($STAMP): add refund helper" \
  --body "Demo PR generated by scripts/demo-pr.sh. Exists to give the grid something to catch."
