from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class AsyncSession:
    async def __aenter__(self) -> "AsyncSession": ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self) -> Any: ...
    def rollback(self) -> Any: ...
    def refresh(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...
    # Synchronous, unlike most of the above: it only marks the identity map
    # dirty. Tests need it because the suite's session maker sets
    # expire_on_commit=False, so a row read before a request keeps its stale
    # values after the app commits on a different session.
    def expire_all(self) -> None: ...

class async_sessionmaker(Generic[_T]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, **kw: Any) -> _T: ...

class AsyncEngine:
    def begin(self, *args: Any, **kwargs: Any) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    async def dispose(self) -> None: ...

def create_async_engine(*args: Any, **kwargs: Any) -> AsyncEngine: ...
def async_engine_from_config(*args: Any, **kwargs: Any) -> AsyncEngine: ...

def __getattr__(name: str) -> Any: ...
